# This workflow listens on new tags, builds the project, pushes an docker image and creates the GitHub release.

name: Release-Handler

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 
        name: Extract release version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -  
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github          
      - 
        name: Build with Maven
        run: mvn verify
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./datagym-backend/
          file: ./datagym-backend/Dockerfile_dhub
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: datagymai/datagym-core:latest,datagymai/datagym-core:${{ env.RELEASE_VERSION }} 
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./datagym-backend/target/datagym.jar
